### ISSUE TITLE
Pantheon

### ISSUE THREAD

**Issue by davidbarratt** [drupal-composer/drupal-composer.github.io#1]
I'm not sure if this is a good idea or not, but it looks like Pantheon will host the project for free (assuming it's on Drupal):
https://pantheon.io/free-website-management-platform-beyond-hosting

**Comment by derhasi** [comment]
Thanks for thinking bout that. But for this site, static html is totally sufficient at the moment. In addition the open workflow on github makes it easy to change the site and we do not have any need to update our site (like security updates). So at the moment, I do not see a reason why to move.

**Comment by webflo** [comment]
Static site ftw.
